const routines={
 morning:{title:'الروتين الصباحي قبل المدرسة',bg:'assets/morning-bg.png',tasks:['🚿 دخول الحمام والوضوء','🪥 غسل الأسنان','🕌 صلاة الصبح','🛏️ ترتيب السرير','👕 لبس ملابس المدرسة','🌸 وضع العطر','💇 تمشيط الشعر','👟 لبس الحذاء','🍱 أخذ اللانشبوكس','💧 أخذ زجاجة الماء']},
 night:{title:'روتيني الليلي',bg:'assets/nightly-bg.png',tasks:['🧹 ترتيب غرفتي','🕌 صلاة العشاء','🤲 أذكار النوم','🍱 وضع اللانشبوكس بالمطبخ','🚿 دخول الحمام','💧 تجهيز زجاجة المياه','📒 التأكد من الواجبات','🎒 تجهيز حقيبة المدرسة','👕 تجهيز ملابس المدرسة','✏️ التأكد من الأدوات']},
 study:{title:'روتيني للمذاكرة',bg:'assets/study-bg.png',tasks:['🪑 تجهيز مكان المذاكرة','✏️ تجهيز الأدوات','📚 إتمام واجبات المدرسة','📝 العمل على واجبات الدرس','🌟 مذاكرة زيادة عن المطلوب','🧹 ترتيب مكان المذاكرة']}
};
const cheers=['أحسنت يا حمزة!','أداء أسطوري يا علي!','ماما فخورة بك يا حمزة!','رائع يا علي!','أنت متميز يا حمزة!','ممتاز يا علي!','أحسنت يا علي!','أداء أسطوري يا حمزة!','ماما فخورة بك يا علي!','رائع يا حمزة!','أنت متميز يا علي!','ممتاز يا حمزة!'];
const facts=[
'🐙 الأخطبوط لديه 3 قلوب، ودمه أزرق.','🦋 الفراشة تستطيع التذوق باستخدام أقدامها.','🦒 لسان الزرافة قد يصل طوله إلى حوالي 50 سم.','🦇 بعض الخفافيش تحدد مكان الأشياء باستخدام الصدى.','🐘 الفيل يستطيع تمييز أصوات أفراد من قطيعه.','🐬 لكل دولفين صفير مميز يشبه الاسم.','🦈 بعض أسماك القرش تستبدل أسنانها باستمرار.','🐝 النحل يستطيع رؤية بعض الألوان التي لا تراها أعيننا.','🌕 آثار أقدام رواد الفضاء على القمر يمكن أن تبقى لفترة طويلة جدًا.','☀️ ضوء الشمس يحتاج حوالي 8 دقائق و20 ثانية ليصل إلى الأرض.','🪐 اليوم على كوكب الزهرة أطول من سنته.','🔴 غروب الشمس على المريخ قد يبدو أزرق اللون.','🌌 عندما نرى مجرة بعيدة جدًا، فنحن نراها كما كانت في الماضي.','🌻 بعض النباتات تستطيع تحريك أوراقها استجابةً للضوء.','🍄 الفطر ليس نباتًا؛ إنه ينتمي إلى مملكة مختلفة.','🌵 الصبار يخزن الماء داخل جسمه.','🌳 بعض الأشجار يمكن أن تعيش آلاف السنين.','🌊 المحيط الهادئ هو أكبر محيط على الأرض.','🏔️ جبل إيفرست هو أعلى نقطة على سطح الأرض فوق مستوى البحر.','🧊 القارة القطبية الجنوبية هي أبرد قارات الأرض.','🇳🇵 علم نيبال هو العلم الوطني الوحيد الذي ليس مستطيلًا.','🇿🇦 جنوب أفريقيا لديها ثلاث عواصم.','🧠 الدماغ يستهلك قدرًا كبيرًا من طاقة الجسم رغم صغر حجمه نسبيًا.','🌈 قوس قزح في الحقيقة جزء من دائرة.','💎 الألماس والفحم يتكونان من الكربون، لكن ترتيب الذرات مختلف.','💧 الماء يمكن أن يكون صلبًا أو سائلًا أو غازًا.','🧊 الماء يتمدد عندما يتجمد، لذلك يطفو الجليد.','🎈 الهيليوم أخف من الهواء، ولذلك يمكنه رفع البالونات.','🌍 المجال المغناطيسي للأرض يساعد في حمايتنا من بعض الجسيمات القادمة من الشمس.','🌟 أحيانًا يؤدي اكتشاف جديد إلى تغيير ما كان العلماء يعتقدونه سابقًا.'
];
const stateKey='routine-hamza-ali-v3';
let state={streak:0,done:{morning:Array.from({length:10},()=>[false,false]),night:Array.from({length:10},()=>[false,false]),study:Array.from({length:6},()=>[false,false])},completedToday:false,reward:false};
let current='';let cheerIndex=0;let audioCache={};let lastCheer={0:'',1:''};let deferredInstallPrompt=null;
function blankDone(){return {morning:Array.from({length:10},()=>[false,false]),night:Array.from({length:10},()=>[false,false]),study:Array.from({length:6},()=>[false,false])}}
function normalize(s){const d=blankDone();if(s&&s.done)for(const k of Object.keys(d)){if(Array.isArray(s.done[k]))s.done[k]=s.done[k].map((x,i)=>Array.isArray(x)?[!!x[0],!!x[1]]:[!!x,!!x]).slice(0,d[k].length);while(s.done[k].length<d[k].length)s.done[k].push([false,false]);d[k]=s.done[k]}return {streak:Number(s?.streak)||0,done:d,completedToday:!!s?.completedToday,reward:!!s?.reward}}
async function load(){try{const r=await window.storage.get(stateKey);if(r?.value)state=normalize(JSON.parse(r.value))}catch(e){state=normalize(state)}}
async function save(){try{await window.storage.set(stateKey,JSON.stringify(state))}catch(e){/* keep working in preview environments */}}
function app(){return document.getElementById('app')}
function shell(){app().innerHTML=`<header class="top"><div class="brand">🌿 روتيني اليومي</div><div class="top-actions"><button id="installBtn" class="install-btn" onclick="installApp()">📲 تثبيت التطبيق</button><div class="streak">🔥 عدد الأيام: <span id="streak">0</span></div></div></header><main id="screens"></main><div id="celebrate" class="celebrate"></div><div id="toast"></div><div id="modal" class="modal"><div class="modal-box"><button class="close" onclick="closeModal()">×</button><h2>هل تعلم؟ 🤓</h2><p id="factText" class="fact"></p><button class="btn primary" style="width:100%" onclick="closeModal()">جميل! ⭐</button></div></div>`}
function setScreen(html,resetScroll=true){const y=window.scrollY;document.getElementById('screens').innerHTML=html;if(resetScroll)window.scrollTo(0,0);else window.scrollTo(0,y);sync()}
function sync(){const s=document.getElementById('streak');if(s)s.textContent=state.streak;const reward=document.getElementById('reward');if(reward)reward.classList.toggle('show',state.reward);const ib=document.getElementById('installBtn');if(ib){const standalone=window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true;ib.style.display=standalone?'none':'';ib.textContent=deferredInstallPrompt?'📲 تثبيت التطبيق':'📲 طريقة التثبيت'}}
function welcome(){setScreen(`<section class="screen active"><div class="hero"><img class="hero-img" src="assets/children.jpg" alt="حمزة وعلي"><h1>يا أبطال حمزة وعلي ✨</h1><p class="sub">يومكما الجميل يبدأ بخطوة</p><p class="question">هل أنتما جاهزان لبدء يومكما يا أبطال؟</p><div class="actions"><button class="btn primary" onclick="goHome()">نعم جاهزان 🚀</button><button class="btn secondary" onclick="confirmReset()">ابدأ من اليوم الأول</button></div></div></section>`)}
function goHome(){setScreen(`<section class="screen active"><div class="hero"><img class="hero-img" src="assets/children.jpg" alt="حمزة وعلي"><h1>ماذا سننجز اليوم؟ 🌟</h1><p class="sub">كل قائمة نكملها = خطوة جديدة!</p></div><div class="cards">${card('morning','☀️','الروتين الصباحي','قبل المدرسة')}${card('night','🌙','روتيني الليلي','قبل النوم')}${card('study','📚','روتيني للمذاكرة','وقت التركيز')}</div><div id="reward" class="reward"><button class="btn" onclick="showFact()">🎁 مكافأة اليوم: هل تعلم؟</button></div>${allComplete()?'<div class="actions"><button class="btn primary" onclick="newDay()">☀️ يوم جديد</button></div>':''}</section>`)}
function card(k,e,t,small){const done=state.done[k].every(x=>x[0]&&x[1]);return `<article class="card ${k}"><div><div class="emoji">${e}</div><h2>${t}</h2><small>${small}</small></div><button ${done?'disabled':''} onclick="openRoutine('${k}')">${done?'تم ✓':'ابدأ القائمة ←'}</button></article>`}
function openRoutine(k){if(state.done[k].every(x=>x[0]&&x[1]))return;current=k;play('assets/bismillah.mp3');renderRoutine()}
function renderRoutine(){const r=routines[current];const completed=state.done[current].filter(x=>x[0]&&x[1]).length;setScreen(`<section class="screen active"><div class="head"><button class="back" onclick="goHome()">← الرئيسية</button><div class="streak">🔥 ${state.streak}</div></div><div class="single-photo"><img class="routine-photo" src="assets/children.jpg" alt="حمزة وعلي"></div><div class="banner" style="background-image:url('${r.bg}')"><h2>${r.title}</h2></div><div class="progress">${completed} من ${r.tasks.length} مهام مكتملة</div><div class="tasks">${r.tasks.map((t,i)=>taskHTML(t,i)).join('')}</div></section>`,false)}
function taskHTML(raw,i){const d=state.done[current][i];const parts=raw.split(' ');const icon=parts.shift();const label=parts.join(' ');return `<div class="task ${d[0]&&d[1]?'done':''}"><span class="task-icon">${icon}</span><span class="task-name">${label}</span><div class="kids"><div class="kid-control"><span class="kid-label ${d[0]?'checked-label':''}">حمزة</span><button class="check ${d[0]?'checked':''}" onclick="toggle(${i},0)">${d[0]?'✓':''}</button></div><div class="kid-control"><span class="kid-label ${d[1]?'checked-label':''}">علي</span><button class="check ${d[1]?'checked':''}" onclick="toggle(${i},1)">${d[1]?'✓':''}</button></div></div></div>`}
async function toggle(i,k){const d=state.done[current][i];d[k]=!d[k];await save();renderRoutine();if(d[k]){play('assets/task-done.mp3');celebrate();const name=k===0?'حمزة':'علي';const options=cheers.filter(x=>x.includes(name)&&x!==lastCheer[k]);const message=options[Math.floor(Math.random()*options.length)]||`أحسنت يا ${name}!`;lastCheer[k]=message;toast(message);if(d[0]&&d[1]&&state.done[current].every(x=>x[0]&&x[1]))setTimeout(finishRoutine,500)}}
async function finishRoutine(){const r=routines[current];if(!state.completedToday&&allComplete()){state.streak++;state.completedToday=true;state.reward=true;await save()}const msg={morning:['صباحكما الآن أجمل من الشمس يا حمزة وعلي!','بدأتما يومكما بنشاط رائع 🌞'],night:['ما شاء الله عليكما يا حمزة وعلي، ليلة سعيدة فقد أنجزتما الكثير!','أحلام سعيدة يا أبطال! 🌙'],study:['ما شاء الله عليكما يا حمزة وعلي، أنتما على طريق التفوق يا أبطال!','استمرا في التعلم والاكتشاف! 📚']}[current];setScreen(`<section class="screen active"><div class="completion" style="background-image:url('${r.bg}')"><div style="font-size:70px">🎉✨</div><h2>${msg[0]}</h2><p>${msg[1]}</p><button class="btn" onclick="goHome()">الصفحة الرئيسية</button></div></section>`)}
function allComplete(){return Object.values(state.done).every(a=>a.every(x=>x[0]&&x[1]))}
async function newDay(){Object.keys(state.done).forEach(k=>state.done[k]=state.done[k].map(()=>[false,false]));state.completedToday=false;state.reward=false;await save();welcome()}
async function confirmReset(){if(confirm('هل تريدان البدء من اليوم الأول؟ سيتم تصفير الستريك وكل المهام.')){state={streak:0,done:blankDone(),completedToday:false,reward:false};await save();welcome()}}
function play(src){try{if(!audioCache[src])audioCache[src]=new Audio(src);audioCache[src].currentTime=0;audioCache[src].play().catch(()=>{})}catch(e){}}
function celebrate(){const box=document.getElementById('celebrate');box.innerHTML='';['🎉','✨','⭐','🌟','🎊','💫','🎈'].forEach((x,i)=>{const s=document.createElement('span');s.className='conf';s.textContent=x;s.style.left=(5+i*13+Math.random()*7)+'%';s.style.animationDelay=(Math.random()*.2)+'s';box.appendChild(s)});setTimeout(()=>box.innerHTML='',1800)}
function toast(t){const old=document.getElementById('toast');old.textContent=t;old.className='toast';void old.offsetWidth;setTimeout(()=>{if(old)old.className=''},4000)}
async function showFact(){if(!state.reward)return;const f=facts[Math.floor(Math.random()*facts.length)];document.getElementById('factText').textContent=f;document.getElementById('modal').classList.add('show');state.reward=false;const reward=document.getElementById('reward');if(reward)reward.classList.remove('show');await save();play('assets/fact-popup.mp3')}
function closeModal(){document.getElementById('modal').classList.remove('show')}
async function installApp(){if(deferredInstallPrompt){deferredInstallPrompt.prompt();const result=await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;sync();return}alert('لتثبيت التطبيق: افتحي قائمة المتصفح ⋮ ثم اختاري «تثبيت التطبيق» أو «إضافة إلى الشاشة الرئيسية». إذا لم يظهر الخيار، افتحي الموقع من Chrome وتأكدّي أن الصفحة تعمل عبر HTTPS.')}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;sync()});
window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;sync()});
async function boot(){shell();await load();welcome();if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{})}sync()}
boot();
